### ISSUE TITLE
Support installation using chocolatey

### ISSUE THREAD

**Issue by amra** [kanekotic/barklarm#11]
Add support to install and upgrade `barklarm` with Chocolatey on Windows. 

That will enable installing/upgrading with only once command.
```
choco install barklarm
```

**Comment by kanekotic** [comment]
Waiting for it to be approved but is done  https://community.chocolatey.org/packages/barklarm/1.7.2, please test it when you have some time @amra

**Comment by amra** [comment]
Tested and it's working.
```
choco install barklarm -s .\barklarm.1.7.2.nupkg
```
